[2025-01-16T09:30:55.510+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T09:30:55.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.transform_data manual__2025-01-16T09:30:39.957952+00:00 [queued]>
[2025-01-16T09:30:55.546+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.transform_data manual__2025-01-16T09:30:39.957952+00:00 [queued]>
[2025-01-16T09:30:55.547+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T09:30:55.560+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): transform_data> on 2025-01-16 09:30:39.957952+00:00
[2025-01-16T09:30:55.566+0000] {standard_task_runner.py:63} INFO - Started process 882 to run task
[2025-01-16T09:30:55.569+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'transform_data', 'manual__2025-01-16T09:30:39.957952+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp_t7m5sf4']
[2025-01-16T09:30:55.570+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask transform_data
[2025-01-16T09:30:55.617+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.transform_data manual__2025-01-16T09:30:39.957952+00:00 [running]> on host airflow-scheduler
[2025-01-16T09:30:55.706+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T09:30:39.957952+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T09:30:39.957952+00:00'
[2025-01-16T09:30:55.708+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T09:30:55.716+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2025-01-16T09:30:55.718+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/transform.py
[2025-01-16T09:30:57.118+0000] {spark_submit.py:641} INFO - 25/01/16 09:30:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16T09:30:58.100+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-01-16T09:30:58.101+0000] {spark_submit.py:641} INFO - File "/spark-scripts/resources/transform.py", line 6, in <module>
[2025-01-16T09:30:58.104+0000] {spark_submit.py:641} INFO - from resources.extract import extract_data_products
[2025-01-16T09:30:58.104+0000] {spark_submit.py:641} INFO - ModuleNotFoundError: No module named 'resources'
[2025-01-16T09:30:58.136+0000] {spark_submit.py:641} INFO - 25/01/16 09:30:58 INFO ShutdownHookManager: Shutdown hook called
[2025-01-16T09:30:58.137+0000] {spark_submit.py:641} INFO - 25/01/16 09:30:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-94446d22-8614-4d3c-813b-82977bf33bd9
[2025-01-16T09:30:58.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T09:30:58.179+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/transform.py. Error code is: 1.
[2025-01-16T09:30:58.183+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=transform_data, run_id=manual__2025-01-16T09:30:39.957952+00:00, execution_date=20250116T093039, start_date=20250116T093055, end_date=20250116T093058
[2025-01-16T09:30:58.197+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task transform_data (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/transform.py. Error code is: 1.; 882)
[2025-01-16T09:30:58.230+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-16T09:30:58.277+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T09:30:58.282+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
