[2025-01-16T16:07:30.980+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T16:07:31.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.transform_data manual__2025-01-16T16:07:16.430180+00:00 [queued]>
[2025-01-16T16:07:31.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.transform_data manual__2025-01-16T16:07:16.430180+00:00 [queued]>
[2025-01-16T16:07:31.099+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T16:07:31.141+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): transform_data> on 2025-01-16 16:07:16.430180+00:00
[2025-01-16T16:07:31.153+0000] {standard_task_runner.py:63} INFO - Started process 597 to run task
[2025-01-16T16:07:31.163+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'transform_data', 'manual__2025-01-16T16:07:16.430180+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpgwkkmg35']
[2025-01-16T16:07:31.170+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask transform_data
[2025-01-16T16:07:31.304+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.transform_data manual__2025-01-16T16:07:16.430180+00:00 [running]> on host airflow-scheduler
[2025-01-16T16:07:31.610+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T16:07:16.430180+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T16:07:16.430180+00:00'
[2025-01-16T16:07:31.614+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T16:07:31.648+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2025-01-16T16:07:31.653+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/transform.py
[2025-01-16T16:07:33.640+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16T16:07:35.081+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SparkContext: Running Spark version 3.3.2
[2025-01-16T16:07:35.111+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO ResourceUtils: ==============================================================
[2025-01-16T16:07:35.112+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-01-16T16:07:35.113+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO ResourceUtils: ==============================================================
[2025-01-16T16:07:35.114+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SparkContext: Submitted application: Data Transform
[2025-01-16T16:07:35.136+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-01-16T16:07:35.147+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO ResourceProfile: Limiting resource is cpu
[2025-01-16T16:07:35.148+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-01-16T16:07:35.200+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SecurityManager: Changing view acls to: airflow
[2025-01-16T16:07:35.201+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SecurityManager: Changing modify acls to: airflow
[2025-01-16T16:07:35.202+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SecurityManager: Changing view acls groups to:
[2025-01-16T16:07:35.202+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SecurityManager: Changing modify acls groups to:
[2025-01-16T16:07:35.203+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-01-16T16:07:35.443+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO Utils: Successfully started service 'sparkDriver' on port 46757.
[2025-01-16T16:07:35.483+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SparkEnv: Registering MapOutputTracker
[2025-01-16T16:07:35.523+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SparkEnv: Registering BlockManagerMaster
[2025-01-16T16:07:35.543+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-01-16T16:07:35.544+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-01-16T16:07:35.549+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-01-16T16:07:35.571+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-631cc3ec-7f76-41ed-9f21-da0c57ceea5f
[2025-01-16T16:07:35.599+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-01-16T16:07:35.619+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-01-16T16:07:35.866+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-01-16T16:07:35.923+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:35 ERROR SparkContext: Failed to add /opt/bitnami/spark/jars/postgresql-42.2.18.jar to Spark environment
[2025-01-16T16:07:35.924+0000] {spark_submit.py:641} INFO - java.io.FileNotFoundException: Jar /opt/bitnami/spark/jars/postgresql-42.2.18.jar not found
[2025-01-16T16:07:35.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1959)
[2025-01-16T16:07:35.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.addJar(SparkContext.scala:2014)
[2025-01-16T16:07:35.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-01-16T16:07:35.927+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-01-16T16:07:35.927+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-01-16T16:07:35.928+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-01-16T16:07:35.928+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-01-16T16:07:35.929+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-01-16T16:07:35.929+0000] {spark_submit.py:641} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-01-16T16:07:35.930+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-01-16T16:07:35.931+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-01-16T16:07:35.931+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-01-16T16:07:35.932+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-01-16T16:07:35.933+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-01-16T16:07:35.933+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-01-16T16:07:35.934+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-01-16T16:07:35.935+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2025-01-16T16:07:35.935+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-01-16T16:07:35.936+0000] {spark_submit.py:641} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-01-16T16:07:35.936+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-01-16T16:07:35.937+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-01-16T16:07:35.938+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-01-16T16:07:36.024+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-01-16T16:07:36.076+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 28 ms (0 ms spent in bootstraps)
[2025-01-16T16:07:36.197+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250116160736-0005
[2025-01-16T16:07:36.204+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42793.
[2025-01-16T16:07:36.205+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO NettyBlockTransferService: Server created on airflow-scheduler:42793
[2025-01-16T16:07:36.206+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-01-16T16:07:36.215+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, airflow-scheduler, 42793, None)
[2025-01-16T16:07:36.219+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO BlockManagerMasterEndpoint: Registering block manager airflow-scheduler:42793 with 434.4 MiB RAM, BlockManagerId(driver, airflow-scheduler, 42793, None)
[2025-01-16T16:07:36.222+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, airflow-scheduler, 42793, None)
[2025-01-16T16:07:36.223+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, airflow-scheduler, 42793, None)
[2025-01-16T16:07:36.413+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:36 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-01-16T16:07:36.573+0000] {spark_submit.py:641} INFO - Extracting data from PostgreSQL (transactions)...
[2025-01-16T16:07:39.044+0000] {spark_submit.py:641} INFO - Transforming data...
[2025-01-16T16:07:55.486+0000] {spark_submit.py:641} INFO - 25/01/16 16:07:55 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:08:10.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:08:10 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:08:25.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:08:25 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:08:40.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:08:40 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:08:55.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:08:55 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:09:10.473+0000] {spark_submit.py:641} INFO - 25/01/16 16:09:10 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:09:25.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:09:25 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:09:40.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:09:40 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:09:55.471+0000] {spark_submit.py:641} INFO - 25/01/16 16:09:55 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:10:10.473+0000] {spark_submit.py:641} INFO - 25/01/16 16:10:10 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:10:25.472+0000] {spark_submit.py:641} INFO - 25/01/16 16:10:25 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-01-16T16:10:29.397+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-01-16T16:10:29.418+0000] {process_utils.py:132} INFO - Sending 15 to group 597. PIDs of all processes in the group: [598, 662, 597]
[2025-01-16T16:10:29.421+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 597
[2025-01-16T16:10:29.426+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-16T16:10:29.428+0000] {spark_submit.py:767} INFO - Sending kill signal to spark-submit
[2025-01-16T16:10:29.433+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T16:10:29.495+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 555, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 604, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-01-16T16:10:29.539+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=transform_data, run_id=manual__2025-01-16T16:07:16.430180+00:00, execution_date=20250116T160716, start_date=20250116T160731, end_date=20250116T161029
[2025-01-16T16:10:29.600+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=598, status='terminated', started='16:07:31') (598) terminated with exit code None
[2025-01-16T16:10:29.601+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=662, status='terminated', started='16:07:33') (662) terminated with exit code None
[2025-01-16T16:10:29.602+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=597, status='terminated', exitcode=2, started='16:07:30') (597) terminated with exit code 2
[2025-01-16T16:10:29.603+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-01-16T16:10:29.636+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
